# .streamlit/secrets.toml

# Google Sheets/Drive service account
# See https://docs.streamlit.io/deploy/streamlit-cloud/connect-to-data-sources/gsheets
gcp_service_account = """
{
  "type": "service_account",
  "project_id": "production-data-app-463103",
  "private_key_id": "375b46308c2fe09c37febc8091c2554de47783a7",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCW6OSmbsztItAf\nJPTke/6GZMr3Z1QA0qqqytrCro+0dprTUpvc4pM1uXL/EU9S7XiNkB7sj/UVaOpV\nLXCkndrrGyOjApU76ZAVOoYCw73UKrlPSMg724/lrzFmWcMsLRPQbeLZTSMWC+PS\nTSQJW3DA0hyl0og1+s8tL41zNmpvzBanlBQQX10l4EyCNrO8T3K7G+QuYjq5hOwz\njOAH8/tQMI9TEyEzWxGcNTIAf8v8CCxZfqR8wPo1jYxgxkJ4igk9NiDZXbBzbFSL\noreBNCa6jGAc3J1ioYSSWvctdr6DbGf0BIiFUrXD/OkgBfrCfumUt+DmJTszp/4Y\nKW0GKZhDAgMBAAECggEAGO81LGy9TmdEpQi5r/Du3qzTvmojvpkQWvT2jVlDZEl+\njnElUKtdMHDKV+u3xBd5pkZMXcDxeU6i/VzrMj/k1pje3AXGu6X9SQyo7NcDzAUd\nJkT71KwUDBrU2jj1nxx5nCQz6bytkex4AZz+Wc9yg2GUGy/8kpK03Z3wTLuOfZcl\nqTg4RMTsxithw5vmOGR7XohE220v82mOxxAd7qyVwR4BelvVPd67xTayQNLoJuXb\nQAB2wI8QDPMp05AnmGXpvz0cVMb68NW/DNfMv6mDDzW1sIGqAtK5GmCp+xqJpUfF\ncsP4GdwIVTwlW6BUF709D99+mv2t1vcc8bQoEe09QQKBgQDEzpVzWmG0vw/pdLxi\nRYlgBsEipqNv0y9FeP78xzM44x/xzOiR9ii+ZhAzTzwml0vzj89/lmmNMd/AWQ95\nYlcOxj4jFgPERf00Vm813RxgGLGfSxefOOzud4Xb8iNZvYrDK9R8E64pPR4LCwfE\n5Z0ADqNcbgTlCKtNhCkYwNsfQQKBgQDETGQGkdzCiOy8A+AlOWJfFtpQuJlY/leV\n25hxlB+oTC99F2Y6U5LcbUztBSPNQeNDEDaFJ6So0JW/Sz7xpGO/OlH9+n/EZL0P\n569TXS+4JY3Nl6mgqWwOeOITtR0SYyU6ko8vNmgCwzctbXphmQAbW2T4KIr8kFy2\nCym3+dwagwKBgHU6TGEqm/pquFKp+zBaFSsCuvYl5kJMu+KY4OG20fb3quZ/1KRk\nyP4ok0vMzZp7En2g0ss/z92PsKTFJ+d4wTyGryp9CX9W5SzQs2uVKjq/WsX0l7x6\nzv54aV6Ky62/rjD1IZtKqbncstGHH3iUAMGw9nOvAPFgCZGhwE0DS0JBAoGAexwl\nx3EHcQIK5sfPdckNhvGALgv4MLYjHBtC+kiZqiVNyzg3pvDvNEtgaW5Fy988trye\nVNhODonywKxiZ45f+HiNH6pRI0zCvgziCnhxCx6SVpR9kANxf4oUz6NQ/k0r9hYg\nss1+Ye0o19bHYBpi1MV3B6P1tvybCJjrqzSK9B0CgYAT8q4d6LZGcm9roh7Rn89I\nMRI0OfRtjFgWUIgoLNSOSucjCEaQhFdS79gQ+49Qd5p/DuzKR2X4SXzcfAB22rer\n/dWaZkQH9JFGlaXIzZc/7w3Qh+aIPj5czUqx++AeYm95Ecdn/9vG8lpyW2qcWaOo\nTMUgHnMl2j4JMnS13OcpXg==\n-----END PRIVATE KEY-----\n",
  "client_email": "production-app-service-56@production-data-app-463103.iam.gserviceaccount.com",
  "client_id": "109394750408103217871",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/production-app-service-56%40production-data-app-463103.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""

machine_params_spreadsheet_name = "Production_Data_Logger"
machine_params_worksheet_name = "Machine_Parameters"

production_orders_spreadsheet_name = "Production_Orders_Database"
production_orders_worksheet_name = "Orders_List"